server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: Shiro
  datasource:
    url: jdbc:mariadb://localhost:3306/shiro?useUnicode=true&characterEncoding=utf8
    username: tabuyos
    password: tabuyos
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      # 配置Dialect
        dialect: com.tabuyos.shiro.config.MariaDBConfig
    show-sql: true
    open-in-view: true
  main:
    allow-bean-definition-overriding: true
#    ansi:
#      enabled: detect
logging:
  config: classpath:log4j2.yml

feign:
  url: 127.0.0.1:8070